services:
    nginx:
      container_name: nginx
      build: ./requirements/nginx/.
      image: nginx:42
      expose:
        -  "443"
      depends_on:
        - wordpress
      volumes:
        - wordpress-volume:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      restart: always

    wordpress:
      container_name: wordpress
      build: ./requirements/wordpress/.
      image: wordpress:42
      expose:
        -  "9000"
      depends_on:
        - mariadb
      volumes:
        - wordpress-volume:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      restart: always

    mariadb:
      container_name: mariadb
      build: ./requirements/mariadb/.
      image: mariadb:42
      expose:
        -  "3306"
      volumes:
        - mariadb-volume:/var/lib/mysql
      networks:
        - inception
      env_file:
        - .env
      restart: always

volumes:
    wordpress-volume:
      name: wordpress-volume
      driver: local
      driver_opts:
        device: ~/data/wordpress-volume 
        o: bind
        type: none

    mariadb-volume:
      name: mariadb-volume
      driver: local
      driver_opts:
        device: ~/data/mariadb-volume 
        o: bind
        type: none

networks:
    inception:
      driver: bridge
      name: inception
